// URLBOX Action Types
export const ON_URL_CHANGE = 'ON_URL_CHANGE';
export const ON_CUSTOM_LINK_CHANGE = 'ON_CUSTOM_LINK_CHANGE';
export const ON_ACQUIRING_SHORT_URL = 'ON_ACQUIRING_SHORT_URL';
export const ON_STATUS_CHANGE = 'ON_STATUS_CHANGE';
export const ON_ERROR = 'ON_ERROR';
export const ON_REDIRECT = 'ON_REDIRECT';
